linuxdeepin/deepin-draw

.packit.yaml
rpm/deepin-draw.spec

This commit contains the specfile for building the official package for Fedora
with a Packit setup.
Ultimately, a unified specfile is targeted for Fedora and any other rpm-based
distributions, e.g. openEuler.
And Packit(https://packit.dev/) is a tool for maintaining specfile within
upstream source. It requires a simple config file(.packit.yaml).
Log:
Signed-off-by: Robin Lee <cheeselee@fedoraproject.org>

feat: Initial packit setup

---

src/frame/ccentralwidget.cpp
src/frame/clefttoolbar.cpp

Description: 工具栏和滑动条宽度一致，导致空出10px颜色很突兀。修改工具栏宽度和滑动条一致
Log: 修改工具栏和滑动条UI
Bug: https://pms.uniontech.com/bug-view-156921.html

fix: 修改工具栏和滑动条UI

---

src/frame/AttributesWidgets/ccolorpickwidget.cpp
src/frame/AttributesWidgets/private/cattributeitemwidget.cpp

Description: 颜色选择框样式为控件，其大小会受限于父类窗口大小，背景会有白色窗口。调整颜色选择框为独立窗口，并修改弹出UI样式。
Log: 颜色选择弹窗的背景问题
Bug: https://pms.uniontech.com/bug-view-156951.html

fix: 颜色选择弹窗的背景问题

---

src/CMakeLists.txt
src/service/x-ddf.xml

Description: update-mime-database通过deepin-draw.xml自动生成x-ddf.xml，无需自己安装该文件
Log: x-ddf.xml文件目录整改

fix: x-ddf.xml文件目录整改

---

src/deepin-draw/attribution/boxlayoutwidget.cpp
src/deepin-draw/drawfiles/mainwindow.cpp
src/drawboard/drawboard/drawboard/gui/drawboard.cpp

1.修复深色模式下，工具栏和属性栏未变为深色的问题
2.取消工具栏和属性栏边框显示
3.调整深色模式下属性栏控件边框UI效果
Log: 修复深色模式下，工具栏和属性栏未变为深色的问题
Bug: https://pms.uniontech.com/bug-view-185285.html

fix: 修复深色模式下，工具栏和属性栏未变为深色的问题

---

src/frame/toptoolbar.cpp
src/widgets/dzoommenucombobox.cpp
src/widgets/dzoommenucombobox.h

添加紧凑模式切换时，标题栏切换百分比按钮
调整大小及布局，DTK在5.6.4版本后提供紧凑
模式接口。
Log: 修复紧凑模式下百分比按钮显示异常
Bug: https://pms.uniontech.com/bug-view-193945.html
Influence: 标题栏

fix: 修复紧凑模式下百分比按钮显示异常

---

src/widgets/dzoommenucombobox.cpp
src/widgets/dzoommenucombobox.h

调整标题栏控件间距，图标和缩放控件间距为32px。
Log: Adjust titlebar spacing in compact mode.
Bug: https://pms.uniontech.com/bug-view-193945.html
Influence: TitleBar

fix: Adjust titlebar spacing in compact mode.

---

src/drawshape/cdrawscene.cpp
src/service/filehander.h

成像质量从100调整为-1，使用默认值成像，因画板背景色为白色，保存alpha通道无意义，因此不保存alpha通道值
Log: 解决图片保存后变为几MB的问题
Bug: https://pms.uniontech.com/bug-view-207563.html

fix: 解决图片保存后变为几MB的问题

---

src/service/filehander.cpp

tif格式图片使用QImageWriter保存，采用LZW压缩格式将压缩数据写入文件
Log: 修复图片保存为tif格式后，文件过大的问题
Bug: https://pms.uniontech.com/bug-view-207563.html

fix: 修复图片保存为tif格式后，文件过大的问题

---

src/deepin-draw/main.cpp

家目录路径被写死，改为QDir:homme()获取家目录路径
Log: 修复家目录更改后，画板启动失败的问题

fix: 修复家目录更改后，画板启动失败的问题

---

src/deepin-draw/drawfiles/mainwindow.cpp

修复【画板】转换为ddf格式的图片无法打开
Bug: https://pms.uniontech.com/bug-view-253321.html
Log: 修复【画板】转换为ddf格式的图片无法打开

fix: 修复【画板】转换为ddf格式的图片无法打开

---

src/service/filehander.cpp

Fix the null pointer reference vulnerability.Use the MD5 check to check the file.
Log: Fix the null pointer reference vulnerability.
Bug: https://pms.uniontech.com/bug-view-252519.html

fix: the null pointer reference vulnerability

---

src/drawshape/drawTools/cpentool.cpp

The entire area is refreshed when drawing
Log: The delay is too high when drawing on a 4k screen
Bug: https://pms.uniontech.com/bug-view-262599.html

fix: too much latency when drawing on 4k screens

---

src/application.cpp

Fix compile error: header file not included.
Log: fix compile error

fix: compile error

---

src/application.cpp
src/application.h
src/deepin-draw/main.cpp

Adapt Treeland, disable kwayland-shell in
Treeland enviroment.
Log: Adapt Treeland.
Influence: Treeland

feat: adapt treeland

---

src/drawboard/drawboard/drawboard/context/pagecontext.cpp

优化保存后关闭提示
Bug: https://pms.uniontech.com/bug-view-269141.html
Log: 优化保存后关闭提示

fix: 优化保存后关闭提示

---

src/frame/cviewmanagement.cpp

Resolve the issue of not being able to repeatedly open ddf files
Log: Resolve the issue of not being able to repeatedly open ddf files
Bug: https://pms.uniontech.com/bug-view-270887.html

fix: Resolve the issue of not being able to repeatedly open ddf files

---

src/deepin-draw/attribution/stylewidgets/cutattributionwidget.cpp
src/deepin-draw/attribution/stylewidgets/cutattributionwidget.h

adjust cut attribute confirm button style and layout (for circle 4)
Log: adjust cut attribute confirm button style and layout (for circle 4)
Bug: https://pms.uniontech.com/bug-view-155955.html

fix: adjust cut attribute confirm button style and layout (for circle 4)

---

src/frame/cgraphicsview.cpp

qt6.8 Adaptation Legacy Issues

fix: qt6.8 Adaptation Legacy Issues

---

src/service/filehander.cpp

Refactor isLegalFile() to use QFileInfo/QDir for simpler path validation:
- Ensure parent directory exists
- Verify path is not a directory
- Remove complex regex parsing
Log: Improved file path validation reliability
Bug: https://pms.uniontech.com/bug-view-303265.html
[fix: Read ddf file data failed](https://github.com/linuxdeepin/deepin-draw/pull/131/commits/ab37029321e5fd290a69fc09b01054a80a5e61be) 
Ensure serialization consistency, after Qt6,
size() uses qsizetype, default 8 bytes.
Log: Fix read ddf file failed.

fix: simplify file path validation

---

src/drawshape/cdrawscene.cpp
src/drawshape/drawTools/cpicturetool.cpp

[fix: can not select image](https://github.com/linuxdeepin/deepin-draw/commit/9988f8c3e7bdb86e1ea3ce63aebb3f0e5414981c) 
As title.
Log: fix can not select image.
Bug: https://pms.uniontech.com/bug-view-304191.html
[fix: can not resize item](https://github.com/linuxdeepin/deepin-draw/commit/4cdeadd58c2f8634e2bb074ac78fbafa6d198c06) 
The default value of QGraphicsItem::type() is changed,
from Type to UserType.
Log: fix can not resize item.
Bug: https://pms.uniontech.com/bug-view-304153.html

fix: can not select image /  resize item

---

arm64/linglong.yaml
linglong.yaml
loong64/linglong.yaml
src/frame/mainwindow.cpp

[fix: can not open image](https://github.com/linuxdeepin/deepin-draw/commit/d39b8651e9409d063e9fd976abf6f375a454cf5c) 
The name filter syntax incorrect.
Log: fix can not open image.
Bug: https://pms.uniontech.com/bug-view-306393.html,
https://pms.uniontech.com/bug-view-306141.html
[fix: update description on linglong.](https://github.com/linuxdeepin/deepin-draw/commit/1e15b547addcb121a6be34d69d7678be91891f62) 
As title.
Log: Update description.
Bug: https://pms.uniontech.com/bug-view-305709.html

fix: can not open image / update description.

---

src/drawshape/drawItems/csizehandlerect.cpp

No resources configured for the renderer, causing the icon to fail to rotate properly.
Log: fix bug
Bug: https://pms.uniontech.com/bug-view-326403.html

fix: Missing rotation
