linuxdeepin/deepin-draw

src/frame/mainwindow.cpp, src/widgets/dialog/cexportimagedialog.cpp, src/widgets/dialog/dialog.cpp, src/widgets/dialog/drawdialog.cpp
窗口图标没有随系统改变
Bug: https://pms.uniontech.com/bug-view-136381.html
Log: 窗口图标没有随系统改
=> fix: 窗口图标没有随系统改变

src/drawshape/drawTools/cmasicotool.cpp, src/frame/ccentralwidget.cpp
工具栏添加可滑动功能
Bug: https://pms.uniontech.com/bug-view-137165.html
Bug: https://pms.uniontech.com/bug-view-137371.html
Log: 公共栏添加可滑动功能
=> fix: 工具栏添加滑动，支持触摸屏滑动和图层问题

src/drawshape/drawTools/ctexttool.cpp, src/frame/ccentralwidget.cpp
修复文本bug
Bug: https://pms.uniontech.com/bug-view-136705.html
Bug: https://pms.uniontech.com/bug-view-137581.html
Log:修复文本bug
=> fix: 修复文本编辑属性光标消失与丢失焦点问题

src/drawshape/drawTools/cpentool.cpp, src/widgets/cspinbox.cpp
修复文本属性调节和画笔样式在维语臧语下显示问题
Bug:https://pms.uniontech.com/bug-view-140377.html
Bug:https://pms.uniontech.com/bug-view-140337.html
Log: 文本属性调节和画笔样式在维语臧语下显示问题
=> fix: 文本属性调节和画笔样式在维语臧语下显示问题

src/drawshape/sitemdata.h, src/service/filehander.cpp, src/service/filehander.h
Bug: https://pms.uniontech.com/bug-view-141009.html
Log: 使用画板无法打开老版本创建的ddf图
=> fix: 使用画板无法打开老版本创建的ddf图

debian/changelog, debian/rules
=> fix: 修改V20构建配置

src/deepin-draw/main.cpp, src/utils/eventlogutils.cpp, src/utils/eventlogutils.h
Description: 提交画板启动时，埋点数据采集需求
Log: 提交画板启动时，埋点数据采集需求
=> feat: 提交画板启动时，埋点数据采集需求

rpm/deepin-draw.spec
These dependencies are no longer in use.
Log: Remove unused dependencies
=> fix: remove unused dependencies

.reuse/dep5, debian/copyright
Description: 补充完善reuse和debian copyright相关声明
Log: 补充完善reuse和debian copyright相关声明
Influence: 无
=> chore: 补充完善reuse和debian copyright相关声明

src/frame/toptoolbar.cpp, src/widgets/dialog/cexportimagedialog.cpp, src/widgets/dzoommenucombobox.cpp
Description: 修改画板导出窗口和标题栏UI
Log: 修改画板导出窗口和标题栏UI
Bug: https://pms.uniontech.com/bug-view-160325.html, 
https:// pms.uniontech.com/bug-view-156927.html
=> fix: 修改画板导出窗口和标题栏UI

src/widgets/dialog/cexportimagedialog.cpp
Description: 修改导出弹框标题字体
Log: 修改导出弹框标题字体
Bug: https://pms.uniontech.com/bug-view-156927.html
=> fix: 修改导出弹框标题字体

src/frame/ccentralwidget.cpp, src/frame/ccentralwidget.h, src/frame/mainwindow.cpp, src/frame/mainwindow.h
Description: 使用windowtitle设置路径和文件名，使用xwininfo命令获取当前窗体正在操作文件名和路径。
Log: 使用windowtitle设置窗口路径和文件名
=> feat: 使用windowtitle设置窗口路径和文件名

.tx/deepin.conf, debian/changelog
Update version to 6.0.3
Log: Update version to 6.0.3
=> chore: Update version to 6.0.3

debian/changelog
update V6.0.5
Log: update V6.0.5
=> chore: update V6.0.5

src/widgets/dzoommenucombobox.cpp
Keep float button align vertical center.
Log: Keep float button align vertical center.
Bug: https://pms.uniontech.com/bug-view-193945.html
Influence: TitleBar
=> fix: Keep float button align vertical center.

src/deepin-draw/widgets/toptoolbar.cpp, src/drawboard/drawboard/widgets/dialog/cexportimagedialog.cpp
修复导出功能完全无效的问题
https://github.com/linuxdeepin/developer-center/issues/4625
=> fix: export action doesn't work at all

src/drawshape/drawTools/cpentool.cpp, src/drawshape/drawTools/cpicturetool.cpp, src/frame/AttributesWidgets/private/blurwidget.cpp, src/frame/AttributesWidgets/private/cattributeitemwidget.cpp, src/frame/AttributesWidgets/private/ccutwidget.cpp, src/frame/ccentralwidget.cpp, src/frame/clefttoolbar.cpp, src/frame/clefttoolbar.h, src/frame/cmultiptabbarwidget.cpp, src/widgets/cspinbox.cpp, src/widgets/dialog/cexportimagedialog.cpp
【UI】 Adapt compact mode
Log: 【UI】 Adapt compact mode
Task: https://pms.uniontech.com/task-view-292059.html
=> feat: 【UI】 Adapt compact mode

src/drawshape/drawTools/cpentool.cpp, src/drawshape/drawTools/cpicturetool.cpp, src/frame/AttributesWidgets/private/blurwidget.cpp, src/frame/AttributesWidgets/private/cattributeitemwidget.cpp, src/frame/AttributesWidgets/private/ccutwidget.cpp, src/frame/ccentralwidget.cpp, src/frame/clefttoolbar.cpp, src/frame/clefttoolbar.h, src/frame/cmultiptabbarwidget.cpp, src/widgets/cspinbox.cpp, src/widgets/dialog/cexportimagedialog.cpp
Update REUSE date
Log: Update REUSE date
=> chore: Update REUSE date

src/application.cpp
This fixes build on Arch Linux.
=> fix: include missing header

debian/changelog
v23 Update version to 6.0.6
Log: v23 Update version to 6.0.6
=> fix: v23 Update version to 6.0.6

debian/changelog
update V7.0.2
Log: update V7.0.2
=> chore: update V7.0.2

debian/changelog
相关PR:
* #91
* #93
* #95
* #96
Log: Update version to 6.0.11
=> chore: Update version to 6.0.11

src/service/filehander.cpp, src/service/filehander.h, translations/deepin-draw.ts, translations/deepin-draw_zh_CN.ts
fix the tips of unable to open file.
Log: fix the tips of unable to open file.
Bug: https://pms.uniontech.com/bug-view-271335.html
=> fix: the tips of unable to open file

src/deepin-draw/widgets/dzoommenucombobox.cpp, src/deepin-draw/widgets/dzoommenucombobox.h, src/deepin-draw/widgets/toptoolbar.cpp, src/drawboard/drawboard/widgets/colorWidget/private/ccolorpanel.cpp, src/drawboard/drawboard/widgets/colorWidget/private/cpickcolorwidget.cpp, src/drawboard/drawboard/widgets/colorWidget/private/cpickcolorwidget.h, src/drawboard/drawboard/widgets/dialog/cexportimagedialog.cpp, src/drawboard/drawboard/widgets/dialog/cexportimagedialog.h
adapt compact mode
Log: adapt compact mode
Bug: https://pms.uniontech.com/bug-view-280101.html, https://pms.uniontech.com/bug-view-280121.html, https://pms.uniontech.com/bug-view-280125.html
=> fix: adapt compact mode

debian/changelog
update version to 7.0.3
Log: update version to 7.0.3
=> chore: update version to 7.0.3

arm64/linglong.yaml, debian/changelog, linglong.yaml, src/application.cpp, src/application.h, src/deepin-draw/main.cpp
remove kwayland-shell env
Log: remove kwayland-shell env
=> fix: remove kwayland-shell env

debian/changelog
update version to 7.0.4
Log: update version to 7.0.4
=> chore: update version to 7.0.4

src/deepin-draw/drawfiles/mainwindow.cpp
replace titlebar option button icon
Log: replace titlebar option button icon
Bug: https://pms.uniontech.com/bug-view-285215.html
=> fix: replace titlebar option button icon

debian/changelog
update version to 7.0.5
Log: update version to 7.0.5
=> chore: update version to 7.0.5

deploy_dep, loong64/linglong.yaml
Adapt linglong for loong64.
Log: Adapt linglong for loong64.
Task: https://pms.uniontech.com/task-view-368689.html
=> chore: Adapt linglong for loong64

src/drawshape/cdrawparamsigleton.cpp
优化保存后关闭提示
Bug: https://pms.uniontech.com/bug-view-269141.html
Log: 优化保存后关闭提示
=> fix: 优化保存后关闭提示

arm64/linglong.yaml, debian/changelog, linglong.yaml, loong64/linglong.yaml
Bump version to 6.5.11
Log: Bump version to 6.5.11
=> chore: Bump version to 6.5.11

arm64/linglong.yaml, debian/changelog, linglong.yaml, loong64/linglong.yaml
Bump version to 6.5.14
Log: Bump version to 6.5.14
=> chore: Bump version to 6.5.14
